import { Injectable, signal } from '@angular/core';

type AppLang = 'fr' | 'en';

const translations: Record<AppLang, Record<string, string>> = {
  fr: {
    tracking: 'Suivi',
    analytics: 'Analytique',
    account: 'Compte',
    overview: 'Aperçu',
    asset: 'Asset',
    usersManagement: 'Gestion Utilisateurs',
    alerts: 'Alertes',
    reports: 'Rapports',
    billing: 'Facturation',
    profile: 'Mon Profil',
    dashboard: 'Tableau de bord',
    logout: 'Déconnexion',
    logoutConfirmTitle: 'Déconnexion',
    logoutConfirmBody: 'Souhaitez-vous vraiment quitter l\'application EMS Volt ?',
    cancel: 'Annuler',
    exit: 'Quitter',
    heroChip: 'DONNÉES EN TEMPS RÉEL · RÉSEAU MONDIAL',
    heroTitleLine1: 'Gérez votre',
    heroTitleAccent: 'Énergie',
    heroTitleDim: 'à l\'échelle mondiale.',
    heroDesc: 'Plateforme EMS de nouvelle génération. Visualisez et pilotez vos actifs industriels en temps réel.',
    secureAccess: 'Accès Sécurisé',
    enterCredentials: 'Entrez vos identifiants pour accéder au dashboard',
    fullName: 'Nom complet',
    email: 'Adresse Email',
    password: 'Mot de passe',
    loginButton: 'Accéder au Dashboard',
    registerButton: 'Créer le compte',
    noAccount: 'Pas encore de compte ?',
    alreadyAccount: 'Déjà un compte ?',
    signUp: 'S\'inscrire',
    signIn: 'Se connecter',
    tls: 'TLS 1.3',
    aes: 'Chiffrement AES-256',
    iso: 'ISO 27001',
    sitesActive: 'Sites actifs',
    availability: 'Disponibilité',
    energyManaged: 'Énergie gérée',
    add: 'Ajouter',
    edit: 'Modifier',
    delete: 'Supprimer',
    confirm: 'Confirmer',
    refresh: 'Rafraîchir',
    addSite: 'Ajouter un Site',
    newUser: 'Nouvel Utilisateur',
    newAccount: 'Nouveau Compte',
    userLabel: 'Utilisateur',
    actionsLabel: 'Actions',
    roleLabel: 'Rôle',
    permissionsLabel: 'Permissions',
    monitoringStatus: 'Monitoring Industriel · Actif',
    networkNode: 'Noeud Réseau',
    lat: 'LAT',
    lon: 'LON',
    alt: 'ALT',
    production: 'Production',
    efficiency: 'Efficacité',
    activeAssets: 'Actifs',
    globalNetwork: 'Réseau mondial',
    totalCapacity: 'Capacité totale',
    languageFr: 'Français',
    languageEn: 'English',

    // sidebar + hierarchy
    siteManagement: 'Gestion des Assets',
    manageAssets: 'Gérez vos assets industriels avec précision.',
    loadingAssets: 'Chargement des Assets...',
    noAssetFound: 'Aucun Asset trouvé',
    createFirstSite: 'Commencez par créer votre premier Site',
    yes: 'Oui',
    no: 'Non',
    deleteItemTitle: 'Supprimer ?',
    deleteAssetQuestion: 'Voulez-vous vraiment supprimer l\'élément {{name}} ?',
    addAsset: 'Ajouter',
    modifyAsset: 'Modifier',
    elementName: 'Nom de l\'élément',
    websocketLink: 'Lien WebSocket (Optionnel)',
    maxCurrent: 'Seuil Intensité Max (A)',
    deleteAlertConfirm: 'Voulez-vous vraiment supprimer cette alerte {{label}} ?',

    // dashboard
    globalDashboardTitle: 'Tableau de Bord Global',
    dashboardSubtitle: 'Surveillance des flux énergétiques industriels.',
    activeLabel: 'ACTIF :',
    updateLabel: 'Mise à jour',
    alertLabel: 'ALERTE',
    alertOverloadDetectedOn: 'Surcharge détectée sur {{asset}}',
    activePower: 'Puissance Active',
    totalEnergy: 'Énergie Totale',
    powerFactor: 'Power Factor',
    frequency: 'Fréquence',
    voltage: 'Tension (V)',
    current: 'Intensité (A)',
    voltageLabel: 'Tension (V)',
    currentLabel: 'Intensité (A)',
    powerLabel: 'Puissance (kW)',
    noDataCollecting: 'Collecte des données en cours...',

    // profile
    myProfile: 'Mon Profil',
    profileSubtitle: 'Gérez vos informations et votre sécurité.',
    processing: 'Traitement en cours...',
    saveProfile: 'Sauvegarder',
    security: 'Sécurité',
    currentPassword: 'Actuel',
    newPassword: 'Nouveau',
    confirmPassword: 'Confirmer',
    changePassword: 'Modifier le mot de passe',
    success: 'Succès',
    ok: 'D\'ACCORD',
    userNotLogged: 'Utilisateur non connecté',
    profileUpdated: 'Vos informations ont été mises à jour avec succès !',
    updateError: 'Erreur lors de la mise à jour',
    passwordsMismatch: 'Les mots de passe ne correspondent pas',
    userUpdatedTitle: 'Utilisateur modifié',
    userUpdatedText: 'Utilisateur mis à jour avec succès.',
    accountCreatedTitle: 'Compte créé',
    accountCreatedText: 'Compte créé avec succès.',
    passwordTooShort: 'Le mot de passe doit contenir au moins 4 caractères',
    passwordChanged: 'Mot de passe modifié avec succès !',
    passwordUpdateError: 'Erreur lors de la modification du mot de passe',

    // user management
    userManagementTitle: 'Gestion des Utilisateurs',
    userManagementSubtitle: 'Administrez les accès et les rôles de la plateforme EMS.',
    emailLabel: 'Email',
    noPermissions: 'Aucune permission disponible pour ce rôle',
    roleCalculated: 'Rôle déterminé automatiquement par les permissions',
    editAccount: 'Modifier',
    confirmDeleteUser: 'Voulez-vous vraiment supprimer l\'utilisateur {{name}} ?',
    adminRole: 'Administrateur',
    energyManagerRole: 'Responsable Énergie',
    agentRole: 'Agent',
    permissionName_VIEW_DASHBOARD: 'Voir le tableau de bord',
    permissionDescription_VIEW_DASHBOARD: 'Accès au tableau de bord principal',
    permissionName_VIEW_CONSUMPTION: 'Voir la consommation',
    permissionDescription_VIEW_CONSUMPTION: 'Voir les données temps réel et historiques',
    permissionName_VIEW_ALERTS: 'Voir les alertes',
    permissionDescription_VIEW_ALERTS: 'Voir les alertes et anomalies',
    permissionName_VIEW_REPORTS: 'Voir les rapports',
    permissionDescription_VIEW_REPORTS: 'Accès aux rapports mensuels/annuels',
    permissionName_VIEW_INVOICES: 'Voir les factures',
    permissionDescription_VIEW_INVOICES: 'Accès aux factures et facturation',
    permissionName_MANAGE_THRESHOLDS: 'Gérer les seuils',
    permissionDescription_MANAGE_THRESHOLDS: 'Modifier les seuils d\'alerte',
    permissionName_MANAGE_ASSETS: 'Gérer les assets',
    permissionDescription_MANAGE_ASSETS: 'Créer/modifier/supprimer les assets',
    permissionName_MANAGE_USERS: 'Gérer les utilisateurs',
    permissionDescription_MANAGE_USERS: 'Créer/modifier/supprimer les utilisateurs',
    permissionName_EXPORT_DATA: 'Exporter les données',
    permissionDescription_EXPORT_DATA: 'Exporter les données en CSV/PDF',
    permissionName_VIEW_BILLING: 'Voir la facturation',
    permissionDescription_VIEW_BILLING: 'Accès aux détails de facturation',

    // alerts
    alertJournal: 'Journal des Alertes',
    alertsSubtitle: 'Historique des dépassements de seuils d\'intensité détectés en temps réel.',
    activeMonitoring: 'Surveillance Active',
    dateTime: 'Date & Heure',
    equipment: 'Équipement',
    messageLabel: 'Message',
    measuredValue: 'Valeur Mesurée',
    hardwareNode: 'Hardware Node',
    thresholdLabel: 'Seuil',
    noAlerts: 'Aucune anomalie détectée dans l\'historique.',
    alertDeleted: 'Alerte supprimée avec succès.',
    alertDeleteError: 'Erreur lors de la suppression de l\'alerte',
    latestAlertNotification: '🔴 DERNIÈRE ALERTE ({{date}} {{time}}) : {{message}} – {{value}}A (Seuil {{threshold}}A)',

    // reports
    reportsTitle: 'Centre d\'Exploitation',
    reportsSubtitle: 'Générez des rapports d\'analyse complets pour chaque point de mesure.',
    reportsReady: 'Rapports Prêts',
    fromLabel: 'Du',
    toLabel: 'Au',
    loadingIndustryAssets: 'Chargement des Assets industriels...',
    analysisVoltageCurrent: 'Analyse Tension / Courant',
    powerSummary: 'Bilan Puissance (TKW)',
    gridStability: 'Stabilité Réseau (Hz)',
    exportPdf: 'Télécharger PDF',
    exportCsv: 'Télécharger CSV',
    reportFilePrefix: 'Rapport',

    // billing
    invoiceFor: 'Facture :',
    monthlySummary: 'Récapitulatif financier mensuel',
    monthLabel: 'Mois',
    yearLabel: 'Année',
    recalculate: 'Recalculer',
    downloadPdf: 'Télécharger PDF',
    designation: 'Désignation / Libellé',
    consumption: 'Consommation',
    unitPrice: 'P.U (DT)',
    amount: 'Montant (DT)',
    activeEnergyLabel: 'Énergie Active (kWh)',
    dayConsumption: 'Consommation Jour',
    peakConsumption: 'Pointe (Matin & Soir)',
    nightConsumption: 'Consommation Nuit',
    powerCharge: 'Redevance Puissance',
    annualFixedPrice: 'Forfait Annuel',
    tvaConsumption: 'TVA sur Consommation (19%)',
    totalNetTTC: 'Total Net TTC',
    billedPeriod: 'Période facturée',
    billedAmount: 'Montant total TTC',
    annualProjection: 'Projection annuelle',
    monthlyAmount: 'Montant TTC par mois (DT)',
    invoiceDetails: 'Consommation facturée en dinars pour l\'asset sélectionné.',
    invoiceTitle: '⚡ FACTURE',
    invoiceEquipment: 'Équipement',
    invoicePeriod: 'Période',
    invoiceIssuedDate: 'Date d\'émission',
    invoiceGeneratedBy: 'Document généré par le système EMS - Energy Management System',
    annualConsumptionChart: 'Diagramme de consommation annuelle',
    voltEMSInfo: 'Volt EMS Intelligence v2.0',

    // thresholds
    thresholdsTitle: 'Seuils d\'Alerte',
    thresholdsSubtitle: 'Configurez les seuils de surveillance',
    addThreshold: 'Ajouter Seuil',
    filterBy: 'Filtrer par :',
    allEquipment: 'Tous les équipements',
    equipmentId: 'Équipement ID',
    activeStatus: '● ACTIF',
    inactiveStatus: '○ INACTIF',
    disable: 'Désactiver',
    enable: 'Activer',
    noThresholds: 'Aucun seuil configuré. Cliquez sur "Ajouter Seuil" pour commencer.',
    addOrEditThreshold: '{{mode}} un Seuil',
    parameterLabel: 'Paramètre',
    minValueLabel: 'Valeur Min',
    maxValueLabel: 'Valeur Max',
    saveThreshold: 'Enregistrer',
    cancelThreshold: 'Annuler',
    voltageMeasure: 'Tension',
    currentMeasure: 'Courant',
    powerMeasure: 'Puissance',
    frequencyMeasure: 'Fréquence',

    // consumption chart
    liveTracking: 'SUIVI EN DIRECT (P, V, I)',
    liveMonitoring: '● LIVE MONITORING',
    historyAnalysis: 'ANALYSE HISTORIQUE',
    day: 'JOUR',
    week: 'SEMAINE',
    month: 'MOIS',
    collectingData: 'Collecte des données en cours...',
    powerKw: 'Puissance (kW)',
    voltageV: 'Tension (V)',
    currentA: 'Intensité (A)',
    powerLegend: 'Puissance',
    voltageLegend: 'Tension',
    currentLegend: 'Intensité',

    // fallback roles and types
    role_ADMIN: 'Administrateur',
    role_RESPONSABLE_ENERGIE: 'Responsable Énergie',
    role_RESP_ENERGIE: 'Responsable Énergie',
    role_AGENT: 'Agent',
    assetType_SITE: 'Site',
    assetType_TGBT: 'TGBT',
    assetType_ARMOIRE: 'Armoire',
    assetType_LIGNE: 'Ligne',
    assetType_EQUIPEMENT: 'Équipement',

    // months
    month_1: 'Janvier',
    month_2: 'Février',
    month_3: 'Mars',
    month_4: 'Avril',
    month_5: 'Mai',
    month_6: 'Juin',
    month_7: 'Juillet',
    month_8: 'Août',
    month_9: 'Septembre',
    month_10: 'Octobre',
    month_11: 'Novembre',
    month_12: 'Décembre',
    month_short_1: 'Jan',
    month_short_2: 'Fév',
    month_short_3: 'Mar',
    month_short_4: 'Avr',
    month_short_5: 'Mai',
    month_short_6: 'Juin',
    month_short_7: 'Juil',
    month_short_8: 'Aoû',
    month_short_9: 'Sep',
    month_short_10: 'Oct',
    month_short_11: 'Nov',
    month_short_12: 'Déc'
  },
  en: {
    tracking: 'Tracking',
    analytics: 'Analytics',
    account: 'Account',
    overview: 'Overview',
    asset: 'Asset',
    usersManagement: 'User Management',
    alerts: 'Alerts',
    reports: 'Reports',
    billing: 'Billing',
    profile: 'My Profile',
    dashboard: 'Dashboard',
    logout: 'Sign Out',
    logoutConfirmTitle: 'Sign Out',
    logoutConfirmBody: 'Do you really want to exit the EMS Volt app?',
    cancel: 'Cancel',
    exit: 'Exit',
    heroChip: 'REAL-TIME DATA · GLOBAL NETWORK',
    heroTitleLine1: 'Manage your',
    heroTitleAccent: 'Energy',
    heroTitleDim: 'at global scale.',
    heroDesc: 'Next-gen EMS platform. Visualize and control your industrial assets in real time.',
    secureAccess: 'Secure Access',
    enterCredentials: 'Enter your credentials to access the dashboard',
    fullName: 'Full Name',
    email: 'Email Address',
    password: 'Password',
    loginButton: 'Access Dashboard',
    registerButton: 'Create Account',
    noAccount: 'Don\'t have an account?',
    alreadyAccount: 'Already have an account?',
    signUp: 'Sign Up',
    signIn: 'Sign In',
    tls: 'TLS 1.3',
    aes: 'AES-256 Encryption',
    iso: 'ISO 27001',
    sitesActive: 'Active Sites',
    availability: 'Availability',
    energyManaged: 'Energy Managed',
    add: 'Add',
    edit: 'Edit',
    delete: 'Delete',
    confirm: 'Confirm',
    refresh: 'Refresh',
    addSite: 'Add Site',
    monitoringStatus: 'Industrial Monitoring · Active',
    networkNode: 'Network Node',
    lat: 'LAT',
    lon: 'LON',
    alt: 'ALT',
    production: 'Production',
    efficiency: 'Efficiency',
    activeAssets: 'Assets',
    globalNetwork: 'Global Network',
    totalCapacity: 'Total Capacity',
    languageFr: 'Français',
    languageEn: 'English',

    siteManagement: 'Asset Management',
    manageAssets: 'Manage your industrial assets with precision.',
    loadingAssets: 'Loading assets...',
    noAssetFound: 'No asset found',
    createFirstSite: 'Start by creating your first Site',
    yes: 'Yes',
    no: 'No',
    deleteItemTitle: 'Delete ?',
    deleteAssetQuestion: 'Do you really want to delete item {{name}} ?',
    addAsset: 'Add',
    modifyAsset: 'Edit',
    elementName: 'Item name',
    websocketLink: 'WebSocket Link (Optional)',
    maxCurrent: 'Max Current Threshold (A)',
    deleteAlertConfirm: 'Do you really want to delete alert {{label}} ?',

    globalDashboardTitle: 'Global Dashboard',
    dashboardSubtitle: 'Monitoring industrial energy flows.',
    activeLabel: 'ACTIVE :',
    updateLabel: 'Updated',
    activePower: 'Active Power',
    totalEnergy: 'Total Energy',
    powerFactor: 'Power Factor',
    frequency: 'Frequency',
    voltage: 'Voltage (V)',
    current: 'Current (A)',
    voltageLabel: 'Voltage (V)',
    currentLabel: 'Current (A)',
    powerLabel: 'Power (kW)',
    noDataCollecting: 'Collecting data...',

    myProfile: 'My Profile',
    profileSubtitle: 'Manage your information and security.',
    processing: 'Processing...',
    saveProfile: 'Save',
    security: 'Security',
    currentPassword: 'Current',
    newPassword: 'New',
    confirmPassword: 'Confirm',
    changePassword: 'Change Password',
    success: 'Success',
    ok: 'OK',
    userNotLogged: 'User not logged in',
    profileUpdated: 'Your information has been updated successfully!',
    updateError: 'Error updating profile',
    passwordsMismatch: 'Passwords do not match',
    passwordTooShort: 'Password must be at least 4 characters',
    passwordChanged: 'Password changed successfully!',
    passwordUpdateError: 'Error updating password',
    userUpdatedTitle: 'User updated',
    userUpdatedText: 'User updated successfully.',
    accountCreatedTitle: 'Account created',
    accountCreatedText: 'Account created successfully.',

    userManagementTitle: 'User Management',
    userManagementSubtitle: 'Administer platform access and roles.',
    emailLabel: 'Email',
    noPermissions: 'No permissions available for this role',
    roleCalculated: 'Role automatically determined by permissions',
    editAccount: 'Edit',
    confirmDeleteUser: 'Do you really want to delete user {{name}} ?',
    adminRole: 'Administrator',
    energyManagerRole: 'Energy Manager',
    agentRole: 'Agent',
    permissionName_VIEW_DASHBOARD: 'View dashboard',
    permissionDescription_VIEW_DASHBOARD: 'Access to the main dashboard',
    permissionName_VIEW_CONSUMPTION: 'View consumption',
    permissionDescription_VIEW_CONSUMPTION: 'View real-time and historical data',
    permissionName_VIEW_ALERTS: 'View alerts',
    permissionDescription_VIEW_ALERTS: 'View alerts and anomalies',
    permissionName_VIEW_REPORTS: 'View reports',
    permissionDescription_VIEW_REPORTS: 'Access monthly/annual reports',
    permissionName_VIEW_INVOICES: 'View invoices',
    permissionDescription_VIEW_INVOICES: 'Access invoices and billing',
    permissionName_MANAGE_THRESHOLDS: 'Manage thresholds',
    permissionDescription_MANAGE_THRESHOLDS: 'Modify alert thresholds',
    permissionName_MANAGE_ASSETS: 'Manage assets',
    permissionDescription_MANAGE_ASSETS: 'Create/edit/delete assets',
    permissionName_MANAGE_USERS: 'Manage users',
    permissionDescription_MANAGE_USERS: 'Create/edit/delete user accounts',
    permissionName_EXPORT_DATA: 'Export data',
    permissionDescription_EXPORT_DATA: 'Export data as CSV/PDF',
    permissionName_VIEW_BILLING: 'View billing',
    permissionDescription_VIEW_BILLING: 'Access billing details',

    alertJournal: 'Alert Journal',
    alertsSubtitle: 'History of threshold breaches detected in real time.',
    activeMonitoring: 'Active Monitoring',
    dateTime: 'Date & Time',
    equipment: 'Equipment',
    messageLabel: 'Message',
    measuredValue: 'Measured Value',
    hardwareNode: 'Hardware Node',
    thresholdLabel: 'Threshold',
    noAlerts: 'No anomalies detected in the history.',
    alertDeleted: 'Alert deleted successfully.',
    alertDeleteError: 'Error deleting alert',
    latestAlertNotification: '🔴 LATEST ALERT ({{date}} {{time}}): {{message}} – {{value}}A (Threshold {{threshold}}A)',
    alertOverloadDetectedOn: 'Overload detected on {{asset}}',

    reportsTitle: 'Operations Center',
    reportsSubtitle: 'Generate full analysis reports for every measurement point.',
    reportsReady: 'Reports Ready',
    fromLabel: 'From',
    toLabel: 'To',
    loadingIndustryAssets: 'Loading industrial assets...',
    analysisVoltageCurrent: 'Voltage / Current analysis',
    powerSummary: 'Power summary (TKW)',
    gridStability: 'Grid stability (Hz)',
    exportPdf: 'Download PDF',
    exportCsv: 'Download CSV',
    reportFilePrefix: 'Report',

    invoiceFor: 'Invoice:',
    monthlySummary: 'Monthly financial summary',
    monthLabel: 'Month',
    yearLabel: 'Year',
    recalculate: 'Recalculate',
    downloadPdf: 'Download PDF',
    designation: 'Designation / Label',
    consumption: 'Consumption',
    unitPrice: 'Unit Price (DT)',
    amount: 'Amount (DT)',
    activeEnergyLabel: 'Active Energy (kWh)',
    dayConsumption: 'Day Consumption',
    peakConsumption: 'Peak (Morning & Evening)',
    nightConsumption: 'Night Consumption',
    powerCharge: 'Power Charge',
    annualFixedPrice: 'Annual Fixed Fee',
    tvaConsumption: 'VAT on Consumption (19%)',
    totalNetTTC: 'Net Total (incl. tax)',
    billedPeriod: 'Billed Period',
    billedAmount: 'Total Amount (incl. tax)',
    annualProjection: 'Annual Projection',
    monthlyAmount: 'Amount per month (DT)',
    invoiceDetails: 'Billed consumption in dinars for the selected asset.',
    invoiceTitle: '⚡ INVOICE',
    invoiceEquipment: 'Equipment',
    invoicePeriod: 'Period',
    invoiceIssuedDate: 'Issue Date',
    invoiceGeneratedBy: 'Document generated by the EMS system - Energy Management System',
    annualConsumptionChart: 'Annual consumption chart',
    voltEMSInfo: 'Volt EMS Intelligence v2.0',

    thresholdsTitle: 'Alert Thresholds',
    thresholdsSubtitle: 'Configure monitoring thresholds',
    addThreshold: 'Add Threshold',
    filterBy: 'Filter by :',
    allEquipment: 'All equipment',
    equipmentId: 'Equipment ID',
    activeStatus: '● ACTIVE',
    inactiveStatus: '○ INACTIVE',
    disable: 'Disable',
    enable: 'Enable',
    noThresholds: 'No threshold configured. Click "Add Threshold" to start.',
    addOrEditThreshold: '{{mode}} a Threshold',
    parameterLabel: 'Parameter',
    minValueLabel: 'Min Value',
    maxValueLabel: 'Max Value',
    saveThreshold: 'Save',
    cancelThreshold: 'Cancel',
    voltageMeasure: 'Voltage',
    currentMeasure: 'Current',
    powerMeasure: 'Power',
    frequencyMeasure: 'Frequency',

    liveTracking: 'LIVE TRACKING (P, V, I)',
    liveMonitoring: '● LIVE MONITORING',
    historyAnalysis: 'HISTORICAL ANALYSIS',
    day: 'DAY',
    week: 'WEEK',
    month: 'MONTH',
    collectingData: 'Collecting data...',
    powerKw: 'Power (kW)',
    voltageV: 'Voltage (V)',
    currentA: 'Current (A)',
    powerLegend: 'Power',
    voltageLegend: 'Voltage',
    currentLegend: 'Current',

    role_ADMIN: 'Administrator',
    role_RESPONSABLE_ENERGIE: 'Energy Manager',
    role_RESP_ENERGIE: 'Energy Manager',
    role_AGENT: 'Agent',
    assetType_SITE: 'Site',
    assetType_TGBT: 'TGBT',
    assetType_ARMOIRE: 'Switchboard',
    assetType_LIGNE: 'Line',
    assetType_EQUIPEMENT: 'Equipment',

    month_1: 'January',
    month_2: 'February',
    month_3: 'March',
    month_4: 'April',
    month_5: 'May',
    month_6: 'June',
    month_7: 'July',
    month_8: 'August',
    month_9: 'September',
    month_10: 'October',
    month_11: 'November',
    month_12: 'December',
    month_short_1: 'Jan',
    month_short_2: 'Feb',
    month_short_3: 'Mar',
    month_short_4: 'Apr',
    month_short_5: 'May',
    month_short_6: 'Jun',
    month_short_7: 'Jul',
    month_short_8: 'Aug',
    month_short_9: 'Sep',
    month_short_10: 'Oct',
    month_short_11: 'Nov',
    month_short_12: 'Dec'
  }
};

@Injectable({ providedIn: 'root' })
export class LanguageService {
  private languageSignal = signal<AppLang>(this.loadSavedLanguage());

  get language() {
    return this.languageSignal;
  }

  setLanguage(lang: AppLang) {
    this.languageSignal.set(lang);
    localStorage.setItem('app_lang', lang);
  }

  translate(key: string, params?: Record<string, string>) {
    const lang = this.languageSignal();
    const value = translations[lang]?.[key] ?? key;
    if (!params) return value;
    return Object.entries(params).reduce(
      (result, [paramKey, paramValue]) => result.replace(new RegExp(`{{${paramKey}}}`, 'g'), paramValue),
      value
    );
  }

  translateMonth(month: number) {
    return this.translate(`month_${month}`);
  }

  translateMonthShort(month: number) {
    return this.translate(`month_short_${month}`);
  }

  translateAssetType(type: string) {
    return this.translate(`assetType_${type}`);
  }

  translateRole(role: string) {
    return this.translate(`role_${role.toUpperCase()}`);
  }

  translatePermissionName(code: string) {
    return this.translate(`permissionName_${code}`);
  }

  translatePermissionDescription(code: string) {
    return this.translate(`permissionDescription_${code}`);
  }

  translateAlertMessage(message: string) {
    const overloadFr = /^Surcharge détectée sur (.+)$/;
    const overloadEn = /^Overload detected on (.+)$/;

    let asset: string | null = null;

    if (overloadFr.test(message)) {
      asset = message.match(overloadFr)?.[1] ?? null;
    } else if (overloadEn.test(message)) {
      asset = message.match(overloadEn)?.[1] ?? null;
    }

    if (asset) {
      return this.translate('alertOverloadDetectedOn', { asset });
    }

    return message;
  }

  private loadSavedLanguage(): AppLang {
    const saved = localStorage.getItem('app_lang');
    if (saved === 'en' || saved === 'fr') return saved;
    return navigator.language.startsWith('en') ? 'en' : 'fr';
  }
}
